leftnav:
- identifier: 0c185b53-287d-b4ae-6367-31b5a34b7ca7
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: b1bb0dea-3673-d188-af13-d6afbec3ae1e
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 194ab01b-7818-d977-961e-8b2c0f8e0135
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: c1392a00-39b3-e910-1c9e-5627e1181797
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 7ba66cab-dcc3-4e7c-91d5-109ead493d49
  name: Projects
  pageRef: /pages/projects
  weight: 50
